# Takes in a JSON file generated by create_transactions.js and passes each
# transaction in the JSON file to bitcoind.
bitcoin = require 'bitcoin'
config = require './config.json'

exports.BitcoinClient = new bitcoin.Client(config.host, config.port, config.username, config.password)

# Was this run from the command line?
if require.main == module
    # Were there enough arguments passed?
    # Show usage information if not.
    if process.argv.length < 3
        console.log "Usage: node send_transactions.js <input file>"
    else
        _callback = (err, txnID) ->
            console.log txnID
            
        # Send each transaction in the passed-in JSON file.
        transactions = require process.argv[2]
        for fromAddress, transaction of transactions
            exports.BitcoinClient.sendRawTransaction(transaction, _callback)
